name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd128bdfe96a439147a72ab4add0ae84b080d61fc19edacea3359ce8d03550ec"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
