name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dd4f76e4af90f244c937bff1b0ae21c05cc656bb9e68fc1f24ff0db7927a744"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
