name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f91a1707936d23e19d8b1641991b697fedfab451dac5b99f282d7508bc5c339"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
