name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3c47c198ac50690a70722e7df253164a2817cbb5cd5d1b0d47084b09b4f4951"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
