name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d701d48bc10e6e8d1923e0bb024afbd81fe5d549e64e55fbec9e9e87e8c7a8d2"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
