name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0be8c365fab79ec8b90c1e14ffed71d61d8c2a83f5da43e617761e0bc0588603"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
