name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f01a48d69a8f3c7b46b0fc6592d88cc407bcd30637ec69dca305f00a4365553"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
