name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5580f6da6525165ef50cc9e6a2543cef7f15141c13accd418585c8baba33d04"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
