name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5801167faa3c6dfe0c30cf0cac81be3817ea26d18baf12590c253effa716c26"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
