name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ee25a9207b02e575bf0781a9433455bc38c9ca457095543cacfd2ddc5b23824"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
