name = "Madness of the skies 2"
version = "v12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b84ad5a63e205bb8da0a06dd0b7721d6891c481b06bb8d74b5c8b25227fe9804"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
